package br.com.fiap.parquimetro.parquimetro.domain.entities.estacionamento;

public class Estacionamento {

    private Long id;
    private String nome;
    private String endereco;
    private String telefone;
    private String email;
    private String cnpj;
    private String razaoSocial;
    private String inscricaoEstadual;
    private String inscricaoMunicipal;
    private String responsavel;
    private String telefoneResponsavel;
    private String emailResponsavel;
    private String observacao;
    private String status;
    private String dataCadastro;
    private String dataAlteracao;
    private String dataExclusao;
    private String dataInativacao;
    private String dataReativacao;
    private String dataAtivacao;
    private String dataDesativacao;
    private String dataUltimaAtivacao;
    private String dataUltimaDesativacao;
    private String dataUltimaInativacao;
    private String dataUltimaReativacao;
    private String dataUltimaExclusao;
    private String dataUltimaAlteracao;
    private String dataUltimoCadastro;
    private String dataUltimaInsercao;
    private String dataUltimaAtualizacao;
    private String dataUltimaExclusaoLogica;
    private String dataUltimaInativacaoLogica;
    private String dataUltimaReativacaoLogica;
    private String dataUltimaDesativacaoLogica;
    private String dataUltimaAtivacaoLogica;
    private String dataUltimaInsercaoLogica;
    private String dataUltimaAtualizacaoLogica;
    private String dataUltimaExclusaoFisica;
    private String dataUltimaInativacaoFisica;
    private String dataUltimaReativacaoFisica;
    private String dataUltimaDesativacaoFisica;
    private String dataUltimaAtivacaoFisica;
    private String dataUltimaInsercaoFisica;
    private String dataUltimaAtualizacaoFisica;
    private String dataUltimaExclusaoLogicaFisica;
    private String dataUltimaInativacaoLogicaFisica;
    private String dataUltimaReativacaoLogicaFisica;
    private String dataUltimaDesativacaoLogicaFisica;
    private String dataUltimaAtivacaoLogicaFisica;
    private String dataUltimaInsercaoLogicaFisica;
}
